source /home/{{ deployment_name }}/{{mode}}/env/bin/activate
export PYTHON_PATH="/home/{{deployment_name}}/{{mode}}/env/"
export DJANGO_SETTINGS_MODULE="{{deployment_name}}.settings.{{ mode }}"
export DJANGO_SECRET_KEY="{{secret_key}}"
export DJANGO_CONFIGURATION="{{mode}}"

export HIKEIT_DB_USER="{{ db_user }}"
export HIKEIT_DB_PASSWORD="{{ db_password }}"
