---
  - name: Copy django upstart template
    template: src=upstart.conf.j2 dest="/etc/init/{{ deployment_name }}_{{ mode }}.conf"
  - name: Copy celery upstart template
    template: src=celery.conf.j2 dest="/etc/init/celery.conf"
